const mongoose = require('mongoose');

const SuggestionSchema = new mongoose.Schema({
  userName: {
    type: String, // Link suggestions to a specific user
    required: true,
	trim:true,
  },
  chartData: [
    {
      category: {
        type: String, // Name of the category (e.g., "Housing")
        required: true,
		trim: true,
      },
      value: {
        type: Number, // Expense value for the category
        required: true,
		min:0,
      },
    },
  ],
  suggestion: {
    type: String, // Text suggestion generated by OpenAI
    required: true,
	trim: true,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

SuggestionSchema.index({ userName: 1 });
module.exports = mongoose.model('SuggestionModel', SuggestionSchema);
